import { assert } from 'node:console';
import * as fs from 'node:fs';
import * as path from 'node:path';

const wasm = fs.readFileSync(
  path.resolve(
    __dirname,
    '../../../target/wasm32-unknown-unknown/release/erc20_token.wasm'
  ),
  null
);

const base64 = wasm.toString('base64');

const result = `
  /* Autogenerated file. Do not edit manually. */
  /* eslint-disable eslint-comments/disable-enable-pair */
  /* eslint-disable eslint-comments/no-unlimited-disable */
  /* eslint-disable */
  /* prettier-ignore */

  const base64 = "${base64}";

  const wasm = new Uint8Array(Buffer.from(base64, 'base64'));

  export default wasm;
`;

fs.writeFileSync(path.resolve(__dirname, '../wasm.ts'), result);

// eslint-disable-next-line import/first
import generatedwasm from '../wasm';

assert(wasm.length === generatedwasm.length, 'Generated data mismatched');

if (wasm.length !== generatedwasm.length) {
  process.exit(-1);
}
