name: ci-cep18-to-remove

on:
  push:
    branches: [master, dev]

  pull_request:
    branches: [master, dev]

jobs:
  # This ci-smart-contract step shall be removed, only for PR passing previous CI/CD checks
  ci-smart-contract:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  # This ci-js-client step shall be removed, only for PR passing previous CI/CD checks
  ci-js-client:
    needs: ci-smart-contract
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
